use OperatorApprovalClass::*;
use OperatorDependencyClass::*;
use OperatorSuggestedCommand::*;

#[rustfmt::skip]
define_operator_errors! {
    ConfigurationMissing { summary: "Operator configuration is missing.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Configuration), approval: None },
    ConfigurationVersionUnsupported { summary: "Operator configuration version is unsupported.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Configuration), approval: None },
    ConfigurationInvalid { summary: "Operator configuration is invalid.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Configuration), approval: None },
    ConfigurationIncompatible { summary: "Operator configuration is incompatible with this binary.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Configuration), approval: None },
    UnsupportedPlatform { summary: "This host platform is unsupported.", retry: Never, remediation: Terminal, command: Some(Status), dependency: None, approval: None },
    DurableStateMissing { summary: "Durable personal-worker state is missing.", retry: AfterRepair, remediation: Repair, command: Some(WorkerInit), dependency: Some(DurableState), approval: None },
    DurableStateUnsafe { summary: "Durable personal-worker state is unsafe.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(DurableState), approval: None },
    DurableStateCorrupt { summary: "Durable personal-worker state is corrupt.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(DurableState), approval: None },
    DurableStateVersionIncompatible { summary: "Durable personal-worker state schema is incompatible with this binary.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(DurableState), approval: None },
    DurableStateRecoveryRequired { summary: "Durable personal-worker state requires recovery before progress.", retry: AfterRepair, remediation: Repair, command: Some(WorkerRunOnce), dependency: Some(DurableState), approval: None },
    DurableStateBusy { summary: "Durable personal-worker state is busy.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(DurableState), approval: None },
    DurableStateRevisionStale { summary: "Durable personal-worker revision is stale.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(DurableState), approval: None },
    DurableStateGenerationStale { summary: "Durable personal-worker queue generation is stale.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(DurableState), approval: None },
    JobDuplicate { summary: "The exact job request is already recorded.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(DurableState), approval: None },
    JobConflict { summary: "The job identity conflicts with different semantics.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(DurableState), approval: None },
    QueueCapacityReached { summary: "The personal-worker queue has reached its accepted capacity.", retry: AfterRefresh, remediation: Refresh, command: Some(QueueList), dependency: Some(DurableState), approval: None },
    CancellationConflict { summary: "The cancellation conflicts with current job state.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(DurableState), approval: None },
    TerminalReplay { summary: "The terminal job result is already recorded.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(DurableState), approval: None },
    RepositoryUnavailable { summary: "The repository is unavailable for exact source discovery.", retry: AfterDependency, remediation: Dependency, command: Some(Status), dependency: Some(Repository), approval: None },
    RepositoryIdentityMismatch { summary: "The repository identity does not match the accepted configuration.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Repository), approval: None },
    RepositoryDirty { summary: "The repository checkout is not clean enough for immutable source discovery.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Repository), approval: None },
    RepositorySourceChanged { summary: "The repository source changed during exact discovery.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(Repository), approval: None },
    LimaUnavailable { summary: "The configured Lima instance is unavailable.", retry: AfterDependency, remediation: Dependency, command: Some(Status), dependency: Some(Lima), approval: None },
    LimaUninitialized { summary: "The configured Lima instance is not initialised.", retry: AfterDependency, remediation: Dependency, command: Some(Status), dependency: Some(Lima), approval: None },
    LimaStarting { summary: "The configured Lima instance is still starting.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(Lima), approval: None },
    LimaBroken { summary: "The configured Lima instance requires repair.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Lima), approval: None },
    LimaStopped { summary: "The configured Lima instance is stopped.", retry: Immediate, remediation: Retry, command: Some(WorkerRunOnce), dependency: Some(Lima), approval: None },
    LimaObservationStale { summary: "The Lima observation is stale.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(Lima), approval: None },
    LimaIdentityMismatch { summary: "The observed Lima identity does not match the accepted configuration.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Lima), approval: None },
    LimaLifecycleBlocked { summary: "The requested Lima lifecycle action is blocked.", retry: AfterDependency, remediation: Dependency, command: Some(Status), dependency: Some(Lima), approval: None },
    RunnerOffline { summary: "The accepted runner is offline.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(RunnerReadiness), approval: None },
    RunnerStarting { summary: "The accepted runner is still starting.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(RunnerReadiness), approval: None },
    RunnerBusy { summary: "The accepted runner is busy.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(RunnerReadiness), approval: None },
    RunnerDraining { summary: "The accepted runner is draining.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(RunnerReadiness), approval: None },
    RunnerObservationStale { summary: "The runner-readiness observation is stale.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(RunnerReadiness), approval: None },
    RunnerIdentityMismatch { summary: "The observed runner identity does not match the accepted configuration.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(RunnerReadiness), approval: None },
    VerificationProfileUnavailable { summary: "The named verification profile is unavailable.", retry: AfterDependency, remediation: Dependency, command: Some(Status), dependency: Some(Repository), approval: None },
    VerificationPlanRefused { summary: "The verification plan was refused by the accepted policy.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Repository), approval: None },
    CapacityRefused { summary: "Execution was refused because accepted host or guest capacity is unavailable.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(RunnerReadiness), approval: None },
    MemoryPressureRefused { summary: "Execution was refused because accepted memory headroom is unavailable.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(RunnerReadiness), approval: None },
    MemoryExhausted { summary: "Execution ended with corroborated memory exhaustion.", retry: Never, remediation: Terminal, command: Some(Status), dependency: None, approval: None },
    VerificationTimeout { summary: "Execution exceeded its accepted timeout.", retry: Never, remediation: Terminal, command: Some(Status), dependency: None, approval: None },
    RunnerLost { summary: "Execution lost the accepted runner.", retry: AfterRefresh, remediation: Refresh, command: Some(WorkerRunOnce), dependency: Some(RunnerReadiness), approval: None },
    TerminalClassificationInconclusive { summary: "The terminal result could not be classified conclusively.", retry: Never, remediation: Terminal, command: Some(Status), dependency: None, approval: None },
    ExecutionFailed { summary: "Execution ended in a bounded failure.", retry: Never, remediation: Terminal, command: Some(Status), dependency: None, approval: None },
    CleanupFailed { summary: "Execution cleanup did not complete safely.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(DurableState), approval: None },
    GithubCredentialRequired { summary: "GitHub observation requires an approved credential boundary.", retry: AfterDependency, remediation: ApprovalRequired, command: None, dependency: Some(Github), approval: Some(CredentialChange) },
    GithubObservationFailed { summary: "GitHub workflow observation failed.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(Github), approval: None },
    GithubReconciliationStale { summary: "GitHub reconciliation evidence is stale.", retry: AfterRefresh, remediation: Refresh, command: Some(Status), dependency: Some(Github), approval: None },
    GithubEventUnsupported { summary: "The GitHub workflow event is unsupported.", retry: Never, remediation: Terminal, command: Some(Status), dependency: Some(Github), approval: None },
    ServiceUnavailable { summary: "The supervised personal-worker service is unavailable.", retry: AfterDependency, remediation: Dependency, command: Some(Status), dependency: Some(Service), approval: None },
    PackageIncompatible { summary: "The installed package is incompatible with the accepted state.", retry: AfterRepair, remediation: Repair, command: Some(Status), dependency: Some(Release), approval: None },
    UpgradeRequired { summary: "A compatible SmolRunner upgrade is required.", retry: AfterDependency, remediation: Dependency, command: Some(Status), dependency: Some(Release), approval: None },
    ReleaseIncompatible { summary: "The release is incompatible with the accepted configuration or state.", retry: Never, remediation: Terminal, command: Some(Status), dependency: Some(Release), approval: None },
    CredentialChangeApprovalRequired { summary: "Credential configuration or rotation requires operator approval.", retry: AfterDependency, remediation: ApprovalRequired, command: None, dependency: None, approval: Some(CredentialChange) },
    OperatorServiceApprovalRequired { summary: "Operator-machine service installation or removal requires approval.", retry: AfterDependency, remediation: ApprovalRequired, command: None, dependency: Some(Service), approval: Some(OperatorService) },
    PaidCapacityApprovalRequired { summary: "Paid capacity changes require operator approval.", retry: AfterDependency, remediation: ApprovalRequired, command: None, dependency: None, approval: Some(PaidCapacity) },
    ExternalPublicationApprovalRequired { summary: "External publication or contact requires operator approval.", retry: AfterDependency, remediation: ApprovalRequired, command: None, dependency: None, approval: Some(ExternalPublication) },
    ReleaseSigningApprovalRequired { summary: "Release signing requires operator approval.", retry: AfterDependency, remediation: ApprovalRequired, command: None, dependency: Some(Release), approval: Some(ReleaseSigning) },
    DestructiveDataChangeApprovalRequired { summary: "A destructive non-test data change requires operator approval.", retry: AfterDependency, remediation: ApprovalRequired, command: None, dependency: Some(DurableState), approval: Some(DestructiveDataChange) },
    IrreversibleMigrationApprovalRequired { summary: "An irreversible migration requires operator approval.", retry: AfterDependency, remediation: ApprovalRequired, command: None, dependency: Some(DurableState), approval: Some(IrreversibleMigration) },
}
